version: "3.9"

services:
  joomla:
    container_name: joomla
    image: joomla
    restart: always
    links:
      - db:mysql
    ports:
      - 8080:80
    environment:
      JOOMLA_DB_HOST: db
      JOOMLA_DB_USER: root
      JOOMLA_DB_PASSWORD: root
  db:
    container_name: mysql
    image: mysql:8.0.30
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_DATABASE=${MYSQL_DBNAME}
    ports:
      - 3306:3306
    volumes:
      - /data:/var/lib/mysql
  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    restart: always
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306
      - PMA_ARBITRARY=1
      - PMA_CONTROLPASS=${PHPMYADMIN_CONTROLPASS}
    ports:
      - 81:80
    depends_on:
      - "db"