version: "3.9"

services:
  db:
    image: mysql:8.0.30
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_DATABASE=${MYSQL_DBNAME}
    ports:
      - "3306:3306"
    volumes:
      - /data:/var/lib/mysql